# Wlacz/wylacz PvP pomiedzy czlonkami gildii
teampvp: false
# Wlacz/wylacz komende /dom
dom-command: true
cuboid:
  # Promien cuboida po zalozeniu gildii
  min-radius: 15
  # Maksymalny promien cuboida po powiekszaniu (/gildia powieksz)
  max-radius: 50
mysql:
  # Twoj adres bazy danych
  adres: localhost
  # Twoja nazwa bazy danych
  baza-danych: openguild
  # Twoj login do bazy danych
  login: root
  # Twoje haslo do bazy danych
  haslo: password
kolortagugildii: '&6'
#Zasada odczytu do ogarniecia id:ilosc:byte
#Albo kompatybilnie z nowymi wersjami Minecrafta to MATERIAL:ilosc:byte
#Lista material tu: http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html
WymaganePrzedmioty:
  - 5:4
  - WOOD:2
  - APPLE:4
  - 6:3
  - 7:2
  - 8:2